name: ingesta-big-data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ingesta:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java (requerido por PySpark)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install requests pandas openpyxl pyspark lxml html5lib beautifulsoup4

      - name: Ejecutar ingesta
        run: python src/ingestion.py

      - name: Ejecutar limpieza
        run: python src/cleaning.py

      - name: Ejecutar enriquecimiento
        run: python src/enrichment.py

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-ingesta-limpieza-enriquecimiento
          path: |
            src/db/ingestion.db
            src/xlsx/ingestion.xlsx
            src/xlsx/cleaned_data.xlsx
            src/xlsx/enriched_data.xlsx
            src/static/auditoria/ingestion.txt
            src/static/auditoria/cleaning_report.txt
            src/static/auditoria/enrichment_report.txt
